id: IBA640A51
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:15:41+00:00'
last_modified: '2022-06-07T16:29:28.059905+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5261
  title: ལུས་སྟོད་གསོ་བ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    6DE1:
      image_group_id: I1KG5285
      title: ''
      total_pages: 188
      order: 1
      base_file: 6DE1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
